// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urbpoknwecnkhnukzxcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyYnBva253ZWNua2hudWt6eGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTI0ODQsImV4cCI6MjA2NTgyODQ4NH0.38IBmkC2qbjxJSkMfK2EOtK2HKdPC93r3LMP_A-vujw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);